server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
      - id: accountModule
        uri: http://localhost:8081/
        predicates:
        - Path=/accounts/**
      - id: loanModule
        uri: http://localhost:8082/
        predicates:
        - Path=/loans/**
      - id: employeeModule
        uri: http://localhost:8085/
        predicates:
        - Path=/employees/**
      - id: userModule
        uri: http://localhost:8089/
        predicates:
        - Path=/users/**
